In [ ]:
# Imports
import requests
import json
from pprint import pprint
from config import api_key

In [ ]:
# Imports for calculations
import pandas as pd
import numpy as np
import os

In [ ]:
import re

In [ ]:
directory = 'resources/'

# 2. List CSV files in the directory
csv_files = [file for file in os.listdir(directory) if file.endswith('.csv')]

# 3. Loop through CSV files and read them into pandas DataFrames
dataframes = {}
for file in csv_files:
    file_path = os.path.join(directory, file)
    df = pd.read_csv(file_path)
    
    # 4. Store DataFrames in a dictionary
    dataframes[file] = df

In [ ]:
file_name_to_display = 'EA-2010.csv'

# Check if the specified file name exists in the dictionary
if file_name_to_display in dataframes:
    # Access the DataFrame using its file name as the key
    ea_2010_df = dataframes[file_name_to_display]
    print(f"DataFrame for '{file_name_to_display}':")
else:
    print(f"No DataFrame found for '{file_name_to_display}'.")

ea_2010_df.head()

In [ ]:
ea_2010_df.columns = [re.sub(r'^\s+', '', col) for col in ea_2010_df.columns]

new_column_names = [
    "state",
    "year",
    "18-24_count",
    "18-24<hs_grad",
    "18-24_hs_grad/equiv",
    "18-24_some_college/associate",
    "18-24_bachelor/higher",
    "25+_count",
    "25+<9th_grade",
    "25+_9th-12th_grade_nongrad",
    "25+_hs_grad/equiv",
    "25+_some_college",
    "25+_associate's",	
    "25+_bachelor's",
    "25+>bachelor",
    "25-34_count",
    "25-34_hs_grad/higher",
    "25-34_bachelor/higher",
    "35-44_count",
    "35-44_hs_grad/higher",
    "35-44_bachelor/higher",
    "45-64_count",
    "45-64_hs_grad/higher",
    "45-64_bachelor/higher",
    "65+_count",
    "65+_hs_grad/higher",
    "65+_bachelor/higher",
    "25+_earnings",
    "25+<hs_grad",
    "25+_hs_grad/equiv",
    "25+_some_college/associate",
    "25+_bachelor's",
    "25+>bachelor"
]
columns_to_delete = "MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2010 INFLATION-ADJUSTED DOLLARS)"

# Use the rename() method to change column names
ea_2010_df.drop(columns=columns_to_delete, inplace=True)
ea_2010_df.columns = new_column_names


# Print the DataFrame to verify changes
ea_2010_df.head()

In [ ]:
column_names = ea_2010_df.columns.tolist()

# Display column names in a vertical list
for column in column_names:
    print(column)

In [ ]:
ea_2010_df.to_csv('resources/clean_ea_2010.csv', index=False)

In [ ]:
file_name_to_display = 'EA-2011.csv'

# Check if the specified file name exists in the dictionary
if file_name_to_display in dataframes:
    # Access the DataFrame using its file name as the key
    ea_2011_df = dataframes[file_name_to_display]
    print(f"DataFrame for '{file_name_to_display}':")
else:
    print(f"No DataFrame found for '{file_name_to_display}'.")

ea_2011_df.head()

In [ ]:
ea_2010_df.columns = [re.sub(r'^\s+', '', col) for col in ea_2010_df.columns]

new_column_names = [
    "state",
    "year",
    "18-24_count",
    "18-24<hs_grad",
    "18-24_hs_grad/equiv",
    "18-24_some_college/associate",
    "18-24_bachelor/higher",
    "25+_count",
    "25+<9th_grade",
    "25+_9th-12th_grade_nongrad",
    "25+_hs_grad/equiv",
    "25+_some_college",
    "25+_associate's",	
    "25+_bachelor's",
    "25+>bachelor",
    "25-34_count",
    "25-34_hs_grad/higher",
    "25-34_bachelor/higher",
    "35-44_count",
    "35-44_hs_grad/higher",
    "35-44_bachelor/higher",
    "45-64_count",
    "45-64_hs_grad/higher",
    "45-64_bachelor/higher",
    "65+_count",
    "65+_hs_grad/higher",
    "65+_bachelor/higher",
    "25+_earnings",
    "25+<hs_grad",
    "25+_hs_grad/equiv",
    "25+_some_college/associate",
    "25+_bachelor's",
    "25+>bachelor"
]
columns_to_delete = "MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)"

# Use the rename() method to change column names
ea_2011_df.drop(columns=columns_to_delete, inplace=True)
ea_2011_df.columns = new_column_names


# Print the DataFrame to verify changes
ea_2011_df.head()

In [ ]:
column_names = ea_2011_df.columns.tolist()

# Display column names in a vertical list
for column in column_names:
    print(column)

In [ ]:
ea_2011_df.to_csv('resources/clean_ea_2011.csv', index=False)

In [ ]:
file_name_to_display = 'EA-2012.csv'

# Check if the specified file name exists in the dictionary
if file_name_to_display in dataframes:
    # Access the DataFrame using its file name as the key
    ea_2012_df = dataframes[file_name_to_display]
    print(f"DataFrame for '{file_name_to_display}':")
else:
    print(f"No DataFrame found for '{file_name_to_display}'.")

ea_2012_df.head()

In [ ]:
ea_2012_df.columns = [re.sub(r'^\s+', '', col) for col in ea_2012_df.columns]

new_column_names = [
    "state",
    "year",
    "18-24_count",
    "18-24<hs_grad",
    "18-24_hs_grad/equiv",
    "18-24_some_college/associate",
    "18-24_bachelor/higher",
    "25+_count",
    "25+<9th_grade",
    "25+_9th-12th_grade_nongrad",
    "25+_hs_grad/equiv",
    "25+_some_college",
    "25+_associate's",	
    "25+_bachelor's",
    "25+>bachelor",
    "25-34_count",
    "25-34_hs_grad/higher",
    "25-34_bachelor/higher",
    "35-44_count",
    "35-44_hs_grad/higher",
    "35-44_bachelor/higher",
    "45-64_count",
    "45-64_hs_grad/higher",
    "45-64_bachelor/higher",
    "65+_count",
    "65+_hs_grad/higher",
    "65+_bachelor/higher",
    "25+_earnings",
    "25+<hs_grad",
    "25+_hs_grad/equiv",
    "25+_some_college/associate",
    "25+_bachelor's",
    "25+>bachelor"
]
columns_to_delete = "MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)"

# Use the rename() method to change column names
ea_2012_df.drop(columns=columns_to_delete, inplace=True)
ea_2012_df.columns = new_column_names


# Print the DataFrame to verify changes
ea_2012_df.head()

In [ ]:
column_names = ea_2012_df.columns.tolist()

# Display column names in a vertical list
for column in column_names:
    print(column)

In [ ]:
ea_2012_df.to_csv('resources/clean_ea_2012.csv', index=False)

In [ ]:
file_name_to_display = 'EA-2013.csv'

# Check if the specified file name exists in the dictionary
if file_name_to_display in dataframes:
    # Access the DataFrame using its file name as the key
    ea_2013_df = dataframes[file_name_to_display]
    print(f"DataFrame for '{file_name_to_display}':")
else:
    print(f"No DataFrame found for '{file_name_to_display}'.")

ea_2013_df.head()

In [ ]:
ea_2010_df.columns = [re.sub(r'^\s+', '', col) for col in ea_2010_df.columns]

new_column_names = [
    "state",
    "year",
    "18-24_count",
    "18-24<hs_grad",
    "18-24_hs_grad/equiv",
    "18-24_some_college/associate",
    "18-24_bachelor/higher",
    "25+_count",
    "25+<9th_grade",
    "25+_9th-12th_grade_nongrad",
    "25+_hs_grad/equiv",
    "25+_some_college",
    "25+_associate's",	
    "25+_bachelor's",
    "25+>bachelor",
    "25-34_count",
    "25-34_hs_grad/higher",
    "25-34_bachelor/higher",
    "35-44_count",
    "35-44_hs_grad/higher",
    "35-44_bachelor/higher",
    "45-64_count",
    "45-64_hs_grad/higher",
    "45-64_bachelor/higher",
    "65+_count",
    "65+_hs_grad/higher",
    "65+_bachelor/higher",
    "25+_earnings",
    "25+<hs_grad",
    "25+_hs_grad/equiv",
    "25+_some_college/associate",
    "25+_bachelor's",
    "25+>bachelor"
]
#columns_to_delete = "MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2013 INFLATION-ADJUSTED DOLLARS)"

# Use the rename() method to change column names
#ea_2013_df.drop(columns=columns_to_delete, inplace=True)
ea_2013_df.columns = new_column_names


# Print the DataFrame to verify changes
ea_2013_df.head()

In [ ]:
# column_names = ea_2013_df.columns.tolist()
# print(column_names)

column_names = ea_2013_df.columns.tolist()

# Display column names in a vertical list
for column in column_names:
    print(column)

In [ ]:
ea_2013_df.to_csv('resources/clean_ea_2013.csv', index=False)

In [ ]:
file_name_to_display = 'EA-2014.csv'

# Check if the specified file name exists in the dictionary
if file_name_to_display in dataframes:
    # Access the DataFrame using its file name as the key
    ea_2014_df = dataframes[file_name_to_display]
    print(f"DataFrame for '{file_name_to_display}':")
else:
    print(f"No DataFrame found for '{file_name_to_display}'.")

ea_2014_df.head()

In [ ]:
ea_2014_df.columns = [re.sub(r'^\s+', '', col) for col in ea_2014_df.columns]

new_column_names = [
    "state",
    "year",
    "18-24_count",
    "18-24<hs_grad",
    "18-24_hs_grad/equiv",
    "18-24_some_college/associate",
    "18-24_bachelor/higher",
    "25+_count",
    "25+<9th_grade",
    "25+_9th-12th_grade_nongrad",
    "25+_hs_grad/equiv",
    "25+_some_college",
    "25+_associate's",	
    "25+_bachelor's",
    "25+>bachelor",
    "25-34_count",
    "25-34_hs_grad/higher",
    "25-34_bachelor/higher",
    "35-44_count",
    "35-44_hs_grad/higher",
    "35-44_bachelor/higher",
    "45-64_count",
    "45-64_hs_grad/higher",
    "45-64_bachelor/higher",
    "65+_count",
    "65+_hs_grad/higher",
    "65+_bachelor/higher",
    "25+_earnings",
    "25+<hs_grad",
    "25+_hs_grad/equiv",
    "25+_some_college/associate",
    "25+_bachelor's",
    "25+>bachelor"
]
#columns_to_delete = "MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2014 INFLATION-ADJUSTED DOLLARS)"

# Use the rename() method to change column names
#ea_2014_df.drop(columns=columns_to_delete, inplace=True)
ea_2014_df.columns = new_column_names


# Print the DataFrame to verify changes
ea_2014_df.head()

In [ ]:
column_names = ea_2014_df.columns.tolist()

# Display column names in a vertical list
for column in column_names:
    print(column)

In [ ]:
ea_2014_df.to_csv('resources/clean_ea_2014.csv', index=False)

In [ ]:
file_name_to_display = 'EA-2015.csv'

# Check if the specified file name exists in the dictionary
if file_name_to_display in dataframes:
    # Access the DataFrame using its file name as the key
    ea_2015_df = dataframes[file_name_to_display]
    print(f"DataFrame for '{file_name_to_display}':")
else:
    print(f"No DataFrame found for '{file_name_to_display}'.")

ea_2015_df.head()

In [ ]:
column_names = ea_2015_df.columns.tolist()

# Display column names in a vertical list
for column in column_names:
    print(column)

In [ ]:
ea_2015_df.columns = [re.sub(r'^\s+', '', col) for col in ea_2015_df.columns]

new_column_names = [
    "state",
    "year",
    "18-24_count",
    "18-24<hs_grad",
    "18-24_hs_grad/equiv",
    "18-24_some_college/associate",
    "18-24_bachelor/higher",
    "25+_count",
    "25+<9th_grade",
    "25+_9th-12th_grade_nongrad",
    "25+_hs_grad/equiv",
    "25+_some_college",
    "25+_associate's",	
    "25+_bachelor's",
    "25+>bachelor",
    "25-34_count",
    "25-34_hs_grad/higher",
    "25-34_bachelor/higher",
    "35-44_count",
    "35-44_hs_grad/higher",
    "35-44_bachelor/higher",
    "45-64_count",
    "45-64_hs_grad/higher",
    "45-64_bachelor/higher",
    "65+_count",
    "65+_hs_grad/higher",
    "65+_bachelor/higher",
    "25+_earnings",
    "25+<hs_grad",
    "25+_hs_grad/equiv",
    "25+_some_college/associate",
    "25+_bachelor's",
    "25+>bachelor"
]
columns_to_delete = "MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2015 INFLATION-ADJUSTED DOLLARS)"

# Use the rename() method to change column names
ea_2015_df.drop(columns=columns_to_delete, inplace=True)
ea_2015_df.columns = new_column_names


# Print the DataFrame to verify changes
ea_2015_df.head()

In [ ]:
column_names = ea_2015_df.columns.tolist()

# Display column names in a vertical list
for column in column_names:
    print(column)

In [ ]:
ea_2015_df.to_csv('resources/clean_ea_2015.csv', index=False)

In [ ]:
file_name_to_display = 'EA-2016.csv'

# Check if the specified file name exists in the dictionary
if file_name_to_display in dataframes:
    # Access the DataFrame using its file name as the key
    ea_2016_df = dataframes[file_name_to_display]
    print(f"DataFrame for '{file_name_to_display}':")
else:
    print(f"No DataFrame found for '{file_name_to_display}'.")

ea_2016_df.head()

In [ ]:
ea_2016_df.columns = [re.sub(r'^\s+', '', col) for col in ea_2016_df.columns]

new_column_names = [
    "state",
    "year",
    "18-24_count",
    "18-24<hs_grad",
    "18-24_hs_grad/equiv",
    "18-24_some_college/associate",
    "18-24_bachelor/higher",
    "25+_count",
    "25+<9th_grade",
    "25+_9th-12th_grade_nongrad",
    "25+_hs_grad/equiv",
    "25+_some_college",
    "25+_associate's",	
    "25+_bachelor's",
    "25+>bachelor",
    "25-34_count",
    "25-34_hs_grad/higher",
    "25-34_bachelor/higher",
    "35-44_count",
    "35-44_hs_grad/higher",
    "35-44_bachelor/higher",
    "45-64_count",
    "45-64_hs_grad/higher",
    "45-64_bachelor/higher",
    "65+_count",
    "65+_hs_grad/higher",
    "65+_bachelor/higher",
    "25+_earnings",
    "25+<hs_grad",
    "25+_hs_grad/equiv",
    "25+_some_college/associate",
    "25+_bachelor's",
    "25+>bachelor"
]
columns_to_delete = "MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS)"

# Use the rename() method to change column names
ea_2016_df.drop(columns=columns_to_delete, inplace=True)
ea_2016_df.columns = new_column_names


# Print the DataFrame to verify changes
ea_2016_df.head()

In [ ]:
column_names = ea_2016_df.columns.tolist()

# Display column names in a vertical list
for column in column_names:
    print(column)

In [ ]:
ea_2016_df.to_csv('resources/clean_ea_2016.csv', index=False)

In [ ]:
file_name_to_display = 'EA-2017.csv'

# Check if the specified file name exists in the dictionary
if file_name_to_display in dataframes:
    # Access the DataFrame using its file name as the key
    ea_2017_df = dataframes[file_name_to_display]
    print(f"DataFrame for '{file_name_to_display}':")
else:
    print(f"No DataFrame found for '{file_name_to_display}'.")

ea_2017_df.head()

In [ ]:
ea_2017_df.columns = [re.sub(r'^\s+', '', col) for col in ea_2017_df.columns]

new_column_names = [
    "state",
    "year",
    "18-24_count",
    "18-24<hs_grad",
    "18-24_hs_grad/equiv",
    "18-24_some_college/associate",
    "18-24_bachelor/higher",
    "25+_count",
    "25+<9th_grade",
    "25+_9th-12th_grade_nongrad",
    "25+_hs_grad/equiv",
    "25+_some_college",
    "25+_associate's",	
    "25+_bachelor's",
    "25+>bachelor",
    "25-34_count",
    "25-34_hs_grad/higher",
    "25-34_bachelor/higher",
    "35-44_count",
    "35-44_hs_grad/higher",
    "35-44_bachelor/higher",
    "45-64_count",
    "45-64_hs_grad/higher",
    "45-64_bachelor/higher",
    "65+_count",
    "65+_hs_grad/higher",
    "65+_bachelor/higher",
    "25+_earnings",
    "25+<hs_grad",
    "25+_hs_grad/equiv",
    "25+_some_college/associate",
    "25+_bachelor's",
    "25+>bachelor"
]
columns_to_delete = "MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS)"

# Use the rename() method to change column names
ea_2017_df.drop(columns=columns_to_delete, inplace=True)
ea_2017_df.columns = new_column_names


# Print the DataFrame to verify changes
ea_2017_df.head()

In [ ]:
column_names = ea_2017_df.columns.tolist()

# Display column names in a vertical list
for column in column_names:
    print(column)

In [ ]:
ea_2017_df.to_csv('resources/clean_ea_2017.csv', index=False)

In [ ]:
file_name_to_display = 'EA-2018.csv'

# Check if the specified file name exists in the dictionary
if file_name_to_display in dataframes:
    # Access the DataFrame using its file name as the key
    ea_2018_df = dataframes[file_name_to_display]
    print(f"DataFrame for '{file_name_to_display}':")
else:
    print(f"No DataFrame found for '{file_name_to_display}'.")

ea_2018_df.head()

In [ ]:
ea_2018_df.columns = [re.sub(r'^\s+', '', col) for col in ea_2018_df.columns]

new_column_names = [
    "state",
    "year",
    "18-24_count",
    "18-24<hs_grad",
    "18-24_hs_grad/equiv",
    "18-24_some_college/associate",
    "18-24_bachelor/higher",
    "25+_count",
    "25+<9th_grade",
    "25+_9th-12th_grade_nongrad",
    "25+_hs_grad/equiv",
    "25+_some_college",
    "25+_associate's",	
    "25+_bachelor's",
    "25+>bachelor",
    "25-34_count",
    "25-34_hs_grad/higher",
    "25-34_bachelor/higher",
    "35-44_count",
    "35-44_hs_grad/higher",
    "35-44_bachelor/higher",
    "45-64_count",
    "45-64_hs_grad/higher",
    "45-64_bachelor/higher",
    "65+_count",
    "65+_hs_grad/higher",
    "65+_bachelor/higher",
    "25+_earnings",
    "25+<hs_grad",
    "25+_hs_grad/equiv",
    "25+_some_college/associate",
    "25+_bachelor's",
    "25+>bachelor"
]
columns_to_delete = "MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2018 INFLATION-ADJUSTED DOLLARS)"

# Use the rename() method to change column names
ea_2018_df.drop(columns=columns_to_delete, inplace=True)
ea_2018_df.columns = new_column_names


# Print the DataFrame to verify changes
ea_2018_df.head()

In [ ]:
column_names = ea_2018_df.columns.tolist()

# Display column names in a vertical list
for column in column_names:
    print(column)

In [ ]:
ea_2018_df.to_csv('resources/clean_ea_2018.csv', index=False)

In [ ]:
file_name_to_display = 'EA-2019.csv'

# Check if the specified file name exists in the dictionary
if file_name_to_display in dataframes:
    # Access the DataFrame using its file name as the key
    ea_2019_df = dataframes[file_name_to_display]
    print(f"DataFrame for '{file_name_to_display}':")
else:
    print(f"No DataFrame found for '{file_name_to_display}'.")

ea_2019_df.head()

In [ ]:
ea_2019_df.columns = [re.sub(r'^\s+', '', col) for col in ea_2019_df.columns]

new_column_names = [
    "state",
    "year",
    "18-24_count",
    "18-24<hs_grad",
    "18-24_hs_grad/equiv",
    "18-24_some_college/associate",
    "18-24_bachelor/higher",
    "25+_count",
    "25+<9th_grade",
    "25+_9th-12th_grade_nongrad",
    "25+_hs_grad/equiv",
    "25+_some_college",
    "25+_associate's",	
    "25+_bachelor's",
    "25+>bachelor",
    "25-34_count",
    "25-34_hs_grad/higher",
    "25-34_bachelor/higher",
    "35-44_count",
    "35-44_hs_grad/higher",
    "35-44_bachelor/higher",
    "45-64_count",
    "45-64_hs_grad/higher",
    "45-64_bachelor/higher",
    "65+_count",
    "65+_hs_grad/higher",
    "65+_bachelor/higher",
    "25+_earnings",
    "25+<hs_grad",
    "25+_hs_grad/equiv",
    "25+_some_college/associate",
    "25+_bachelor's",
    "25+>bachelor"
]
columns_to_delete = "MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)"

# Use the rename() method to change column names
ea_2019_df.drop(columns=columns_to_delete, inplace=True)
ea_2019_df.columns = new_column_names


# Print the DataFrame to verify changes
ea_2019_df.head()

In [ ]:
column_names = ea_2019_df.columns.tolist()

# Display column names in a vertical list
for column in column_names:
    print(column)

In [ ]:
ea_2019_df.to_csv('resources/clean_ea_2019.csv', index=False)

In [ ]:
file_name_to_display = 'EA-2021.csv'

# Check if the specified file name exists in the dictionary
if file_name_to_display in dataframes:
    # Access the DataFrame using its file name as the key
    ea_2021_df = dataframes[file_name_to_display]
    print(f"DataFrame for '{file_name_to_display}':")
else:
    print(f"No DataFrame found for '{file_name_to_display}'.")

ea_2021_df.head()

In [ ]:
ea_2021_df.columns = [re.sub(r'^\s+', '', col) for col in ea_2021_df.columns]

new_column_names = [
    "state",
    "year",
    "18-24_count",
    "18-24<hs_grad",
    "18-24_hs_grad/equiv",
    "18-24_some_college/associate",
    "18-24_bachelor/higher",
    "25+_count",
    "25+<9th_grade",
    "25+_9th-12th_grade_nongrad",
    "25+_hs_grad/equiv",
    "25+_some_college",
    "25+_associate's",	
    "25+_bachelor's",
    "25+>bachelor",
    "25-34_count",
    "25-34_hs_grad/higher",
    "25-34_bachelor/higher",
    "35-44_count",
    "35-44_hs_grad/higher",
    "35-44_bachelor/higher",
    "45-64_count",
    "45-64_hs_grad/higher",
    "45-64_bachelor/higher",
    "65+_count",
    "65+_hs_grad/higher",
    "65+_bachelor/higher",
    "25+_earnings",
    "25+<hs_grad",
    "25+_hs_grad/equiv",
    "25+_some_college/associate",
    "25+_bachelor's",
    "25+>bachelor"
]
columns_to_delete = "MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2021 INFLATION-ADJUSTED DOLLARS)"

# Use the rename() method to change column names
ea_2021_df.drop(columns=columns_to_delete, inplace=True)
ea_2021_df.columns = new_column_names


# Print the DataFrame to verify changes
ea_2021_df.head()

In [ ]:
column_names = ea_2021_df.columns.tolist()

# Display column names in a vertical list
for column in column_names:
    print(column)

In [ ]:
ea_2021_df.to_csv('resources/clean_ea_2021.csv', index=False)

In [ ]:
file_name_to_display = 'EA-2022.csv'

# Check if the specified file name exists in the dictionary
if file_name_to_display in dataframes:
    # Access the DataFrame using its file name as the key
    ea_2022_df = dataframes[file_name_to_display]
    print(f"DataFrame for '{file_name_to_display}':")
else:
    print(f"No DataFrame found for '{file_name_to_display}'.")

ea_2022_df.head()

In [ ]:
ea_2022_df.columns = [re.sub(r'^\s+', '', col) for col in ea_2022_df.columns]

new_column_names = [
    "state",
    "year",
    "18-24_count",
    "18-24<hs_grad",
    "18-24_hs_grad/equiv",
    "18-24_some_college/associate",
    "18-24_bachelor/higher",
    "25+_count",
    "25+<9th_grade",
    "25+_9th-12th_grade_nongrad",
    "25+_hs_grad/equiv",
    "25+_some_college",
    "25+_associate's",	
    "25+_bachelor's",
    "25+>bachelor",
    "25-34_count",
    "25-34_hs_grad/higher",
    "25-34_bachelor/higher",
    "35-44_count",
    "35-44_hs_grad/higher",
    "35-44_bachelor/higher",
    "45-64_count",
    "45-64_hs_grad/higher",
    "45-64_bachelor/higher",
    "65+_count",
    "65+_hs_grad/higher",
    "65+_bachelor/higher",
    "25+_earnings",
    "25+<hs_grad",
    "25+_hs_grad/equiv",
    "25+_some_college/associate",
    "25+_bachelor's",
    "25+>bachelor"
]
columns_to_delete = "MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)"

# Use the rename() method to change column names
ea_2022_df.drop(columns=columns_to_delete, inplace=True)
ea_2022_df.columns = new_column_names


# Print the DataFrame to verify changes
ea_2022_df.head()

In [ ]:
column_names = ea_2022_df.columns.tolist()

# Display column names in a vertical list
for column in column_names:
    print(column)

In [ ]:
ea_2022_df.to_csv('resources/clean_ea_2022.csv', index=False)